[config]
# 应用名
app_title = 'DeepResearch'
# dev/prod
launch_mode = "prod"
# 日志保存路径
log_filepath = "../logs/frontend.log"
# log level
log_level = "DEBUG"
# 服务启动host
host = '0.0.0.0'
# 服务启动端口
port = 8101
# 用户最大输入
max_input_length = 16384
# agno agentos启动url
agno_agentos_url = "http://10.4.10.226:8102"
agno_id = "deep-research-pipeline"
agno_type = 'workflows'
agno_agentos_jwt_secret = 'Yv7uMsDu6ebYt28U8qRm39s8DKoW8yoaDlKdf2ikDMjkZcts1rHLej7BfqK3sl18'

[document]
document_max_token = 10000
vision_model_base_url = 'http://10.199.7.162:8007/v1'
vision_model_api_key = 'YaUaqKxXK7pSGKhlXdJC'
